### ISSUE TITLE
JOSS Review -- Remove option for 3-dimensional GRF in interactive mode

### ISSUE THREAD

**Issue by gchure** [parafields/parafields#143]
Hi @dokempf, I'm [reviewing your paper for JOSS](https://github.com/openjournals/joss-reviews/issues/5735) and am opening issues as I go along through my checklist. This comment pertains to a feature suggestion for interactive mode. 

I found your tool for interactively generating random fields to be i) fun and ii) very useful. However, you provide an option for 3-dimensional field specification that has no actual utility in interactive mode: 
<img width="912" alt="Screenshot 2023-11-18 at 13 10 08" src="https://github.com/parafields/parafields/assets/6775595/6a6e7149-0ea3-4e2b-892a-27ca487078ee">

Why not just remove Dimension: 3 as an option in the dropdown?  I think [this is the offending line](https://github.com/parafields/parafields/blob/84c17d4399a7b3f24df90e87c9e397418b692bf4/src/parafields/interactive.py#L160C1-L160C58) that could just use an extra logic test to prevent its population.

**Comment by dokempf** [comment]
The rationale here was that while a visualization is not available, the widget UI still gives an intuitive grasp of the available parameter space. I would therefore like to keep it.

**Comment by gchure** [comment]
That sounds fair. I think it would help if you acknowledge this with an `attention` admonition on the [documentation page](https://parafields.readthedocs.io/en/latest/interactive.html).
