### ISSUE TITLE
JOSS Review -- Improve test coverage for FEniCSx integration

### ISSUE THREAD

**Issue by gchure** [parafields/parafields#144]
Hi @dokempf, I'm [reviewing your paper for JOSS](https://github.com/openjournals/joss-reviews/issues/5735) and am opening issues as I go along through my checklist. These comments pertain to test coverage.

The parafields documentation highlights [integration with FEniCSx-based PDE solvers](https://parafields.readthedocs.io/en/latest/intro.html) and [even gives an example of how to use it](https://github.com/parafields/parafields/blob/main/jupyter/fenicsx.ipynb), yet the relevant function: 
https://github.com/parafields/parafields/blob/84c17d4399a7b3f24df90e87c9e397418b692bf4/src/parafields/field.py#L736

[has zero test coverage](https://app.codecov.io/gh/parafields/parafields/blob/main/src%2Fparafields%2Ffield.py#L736). As this is advertised as a feature, it should have some code coverage.

**Comment by dokempf** [comment]
For context: The reason this is currently not properly tested in CI is that FEniCS is not `pip`-installable and it would require a change (to the worse) to the dev installation instructions. You are of course right that this should be done @gchure, but I went with Patrick's suggestion to document the testing status for now (and hope for `pip`-installable FeniCSx)

**Comment by gchure** [comment]
This sounds good to me, and I'll keep my fingers crossed for `pip install fenicsx`.
